### ISSUE TITLE
NOS Plugin not loaded ?

### ISSUE THREAD

**Issue by network-shark** [fakenos/fakenos#20]
Hey 

I am trying to extend a NOS Plugin , but it seems my changes are not loaded to the server. 

I copied the cisco ios example from 

https://fakenos.github.io/fakenos/development/creating_nos_plugin/#create-nos-plugin-from-a-python-file

And tried to add "configure terminal" or "config" to the class , but it seems the driver does not load my extension but is using the default instead. 

I can also provide a plugin which does not exists  . It still works but without my added command.

for example

typo
```
       plugin: /home/sschaack/python/fakenos/my_fake_ios.py1 
```
exits
```
       plugin: /home/sschaack/python/fakenos/my_fake_ios.py
```

under commands I added 
```
    "config": {
        "output": None
        "new_prompt": CONFIG_PROMPT,
        "help": "Enters Config Mode",
        "prompt": [ENABLE_PROMPT],
    },


```
starting server 
inventory 
fakenos -i inventory.yaml
```
hosts:
  #    R1:
  #        username: sharky
  #        password: cisco1234
  #        port: 8000
  #        nos:
  #          plugin: /home/sschaack/python/fakenos/FakeNOSTEST.yaml

    R3:
        username: sharky
        password: cisco1234
        platform: cisco_ios
        port: 6000
        nos:
          #            plugin: /home/sschaack/python/fakenos/my_nos.yaml
          #  plugin: /home/sschaack/python/fakenos/FakeNOSTEST.yaml
            plugin: /home/sschaack/python/fakenos/my_fake_ios.py

```

```
Custom SSH Shell
R3>config
Unknown command
R3>enable
null
R3#config
Unknown command
```
