### ISSUE TITLE
Cannot ssh to devices when running fakenos inside container

### ISSUE THREAD

**Issue by ansiblejunky** [fakenos/fakenos#22]
Trying to run `fakenos` inside a container but having trouble accessing the device that's configured.

Dockerfile:
```
FROM python:3.12-alpine
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install fakenos
WORKDIR /app
COPY . /app

CMD ["python3", "app.py"]
```

network.yaml:
```
hosts:
  R1:
    username: admin
    password: admin
    platform: cisco_ios
    port: 6000
```

app.py:
```
from fakenos import FakeNOS
network_os = FakeNOS(inventory='network.yaml')
network_os.start()
```

docker-compose.yaml:
```
---
name: test
networks:
  default:
    name: example.com

services:
  target:
    image: ansible-fake-switch
    privileged: true
    ports:
      - "12723:6000"
 ```

terminal attempt:
```
ssh -p 12723 admin@localhost
Connection closed by ::1 port 12723
```

From my research something in `fakenos` might be causing this. 
I've tested the same `network.yaml` and `app.py` locally (no container) and it works great.
Thanks for any advice here
