### ISSUE TITLE
short words like no and yes are no recognized as a command

### ISSUE THREAD

**Issue by network-shark** [fakenos/fakenos#25]
Hey , 

I am trying to do something like this .  The command no is not recognized as a command , but if I just do nonono: it works ... 

```
R3#reload in 120
System configuration has been modified. Save? [yes/no]: no
% Invalid input detected at '^' marker.
System configuration has been modified. Save? [yes/no]: nonono
R3#reload in 120
System configuration has been modified. Save? [yes/no]: yes
% Invalid input detected at '^' marker.
System configuration has been modified. Save? [yes/no]: yesyesyes
R3#
```

My custom plugin looks like this. 

```
  reload in 120:
    output: ""
    help: "reloading"
    prompt:
    - "{base_prompt}#"
    - "{base_prompt}>"
    new_prompt: "System configuration has been modified. Save? [yes/no]: "

  no:
      output: ""
      help: "."
      new_prompt: "{base_prompt}#"
      prompt:
        - "System configuration has been modified. Save? [yes/no]: "

  nonono:
      output: ""
      help: "."
      new_prompt: "{base_prompt}#"
      prompt:
        - "System configuration has been modified. Save? [yes/no]: "
```
