### ISSUE TITLE
Implement different key-exchange methods

### ISSUE THREAD

**Issue by evilmonkey19** [fakenos/fakenos#8]
In real case scenarios, many times, there are devices which doesn't have normal key-exchange methods. In my personal experience, even though it is not really common, it happens some time to time that Netmiko does not support out-of-the-box certain key-exchange method. It would be awesome to replicate such cases easily.

There is a need by other people: https://github.com/ktbyers/netmiko/issues/1742

The syntax I propose should something like this:
```yaml
hosts:
    router1:
        username: user
        password: user
        platform: cisco_ios
        port: 8000
        kex_method: diffie-hellman...bla...bla...bla
```
